// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm1cbvzWLWykEAEP9odYy0o9HPwesr1sY',
    appId: '1:739979970700:web:3b3a8784889a23eed853a9',
    messagingSenderId: '739979970700',
    projectId: 'savora-restaurant-apps',
    authDomain: 'savora-restaurant-apps.firebaseapp.com',
    storageBucket: 'savora-restaurant-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrnLCVedkeVpnOmNxDNl2AvQiqE57-YbY',
    appId: '1:739979970700:android:a8f4fb43a089cd29d853a9',
    messagingSenderId: '739979970700',
    projectId: 'savora-restaurant-apps',
    storageBucket: 'savora-restaurant-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsDgyMWmFG1SAWOyO4MHLzNdcL0KByye4',
    appId: '1:739979970700:ios:0d4c0b1c2a1786d1d853a9',
    messagingSenderId: '739979970700',
    projectId: 'savora-restaurant-apps',
    storageBucket: 'savora-restaurant-apps.firebasestorage.app',
    iosBundleId: 'com.example.testClineRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsDgyMWmFG1SAWOyO4MHLzNdcL0KByye4',
    appId: '1:739979970700:ios:0d4c0b1c2a1786d1d853a9',
    messagingSenderId: '739979970700',
    projectId: 'savora-restaurant-apps',
    storageBucket: 'savora-restaurant-apps.firebasestorage.app',
    iosBundleId: 'com.example.testClineRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm1cbvzWLWykEAEP9odYy0o9HPwesr1sY',
    appId: '1:739979970700:web:dc6576119d7e151cd853a9',
    messagingSenderId: '739979970700',
    projectId: 'savora-restaurant-apps',
    authDomain: 'savora-restaurant-apps.firebaseapp.com',
    storageBucket: 'savora-restaurant-apps.firebasestorage.app',
  );
}
